[build]
  functions = "functions"

[dev]
  publish = "dist"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/api"
  status = 200
